# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'for_project.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 364)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.screen = QtWidgets.QTextEdit(self.centralwidget)
        self.screen.setGeometry(QtCore.QRect(-10, 300, 621, 41))
        self.screen.setObjectName("screen")
        self.line1_place1 = QtWidgets.QPushButton(self.centralwidget)
        self.line1_place1.setGeometry(QtCore.QRect(80, 70, 51, 31))
        self.line1_place1.setObjectName("line1_place1")
        self.line1 = QtWidgets.QTextEdit(self.centralwidget)
        self.line1.setGeometry(QtCore.QRect(10, 70, 61, 31))
        self.line1.setObjectName("line1")
        self.line2 = QtWidgets.QTextEdit(self.centralwidget)
        self.line2.setGeometry(QtCore.QRect(10, 110, 61, 31))
        self.line2.setObjectName("line2")
        self.line3 = QtWidgets.QTextEdit(self.centralwidget)
        self.line3.setGeometry(QtCore.QRect(10, 150, 61, 31))
        self.line3.setObjectName("line3")
        self.line4 = QtWidgets.QTextEdit(self.centralwidget)
        self.line4.setGeometry(QtCore.QRect(10, 190, 61, 31))
        self.line4.setObjectName("line4")
        self.line5 = QtWidgets.QTextEdit(self.centralwidget)
        self.line5.setGeometry(QtCore.QRect(10, 230, 61, 31))
        self.line5.setObjectName("line5")
        self.line2_place1 = QtWidgets.QPushButton(self.centralwidget)
        self.line2_place1.setGeometry(QtCore.QRect(80, 110, 51, 31))
        self.line2_place1.setObjectName("line2_place1")
        self.line3_place1 = QtWidgets.QPushButton(self.centralwidget)
        self.line3_place1.setGeometry(QtCore.QRect(80, 150, 51, 31))
        self.line3_place1.setObjectName("line3_place1")
        self.line4_place1 = QtWidgets.QPushButton(self.centralwidget)
        self.line4_place1.setGeometry(QtCore.QRect(80, 190, 51, 31))
        self.line4_place1.setObjectName("line4_place1")
        self.line5_place1 = QtWidgets.QPushButton(self.centralwidget)
        self.line5_place1.setGeometry(QtCore.QRect(80, 230, 51, 31))
        self.line5_place1.setObjectName("line5_place1")
        self.line5_place2 = QtWidgets.QPushButton(self.centralwidget)
        self.line5_place2.setGeometry(QtCore.QRect(130, 230, 51, 31))
        self.line5_place2.setObjectName("line5_place2")
        self.line4_place2 = QtWidgets.QPushButton(self.centralwidget)
        self.line4_place2.setGeometry(QtCore.QRect(130, 190, 51, 31))
        self.line4_place2.setObjectName("line4_place2")
        self.line3_place2 = QtWidgets.QPushButton(self.centralwidget)
        self.line3_place2.setGeometry(QtCore.QRect(130, 150, 51, 31))
        self.line3_place2.setObjectName("line3_place2")
        self.line1_place2 = QtWidgets.QPushButton(self.centralwidget)
        self.line1_place2.setGeometry(QtCore.QRect(130, 70, 51, 31))
        self.line1_place2.setObjectName("line1_place2")
        self.line2_place2 = QtWidgets.QPushButton(self.centralwidget)
        self.line2_place2.setGeometry(QtCore.QRect(130, 110, 51, 31))
        self.line2_place2.setObjectName("line2_place2")
        self.line5_place3 = QtWidgets.QPushButton(self.centralwidget)
        self.line5_place3.setGeometry(QtCore.QRect(180, 230, 51, 31))
        self.line5_place3.setObjectName("line5_place3")
        self.line4_place3 = QtWidgets.QPushButton(self.centralwidget)
        self.line4_place3.setGeometry(QtCore.QRect(180, 190, 51, 31))
        self.line4_place3.setObjectName("line4_place3")
        self.line3_place3 = QtWidgets.QPushButton(self.centralwidget)
        self.line3_place3.setGeometry(QtCore.QRect(180, 150, 51, 31))
        self.line3_place3.setObjectName("line3_place3")
        self.line1_place3 = QtWidgets.QPushButton(self.centralwidget)
        self.line1_place3.setGeometry(QtCore.QRect(180, 70, 51, 31))
        self.line1_place3.setObjectName("line1_place3")
        self.line2_place3 = QtWidgets.QPushButton(self.centralwidget)
        self.line2_place3.setGeometry(QtCore.QRect(180, 110, 51, 31))
        self.line2_place3.setObjectName("line2_place3")
        self.line5_place4 = QtWidgets.QPushButton(self.centralwidget)
        self.line5_place4.setGeometry(QtCore.QRect(230, 230, 51, 31))
        self.line5_place4.setObjectName("line5_place4")
        self.line4_place4 = QtWidgets.QPushButton(self.centralwidget)
        self.line4_place4.setGeometry(QtCore.QRect(230, 190, 51, 31))
        self.line4_place4.setObjectName("line4_place4")
        self.line3_place4 = QtWidgets.QPushButton(self.centralwidget)
        self.line3_place4.setGeometry(QtCore.QRect(230, 150, 51, 31))
        self.line3_place4.setObjectName("line3_place4")
        self.line1_place4 = QtWidgets.QPushButton(self.centralwidget)
        self.line1_place4.setGeometry(QtCore.QRect(230, 70, 51, 31))
        self.line1_place4.setObjectName("line1_place4")
        self.line2_place4 = QtWidgets.QPushButton(self.centralwidget)
        self.line2_place4.setGeometry(QtCore.QRect(230, 110, 51, 31))
        self.line2_place4.setObjectName("line2_place4")
        self.line5_place5 = QtWidgets.QPushButton(self.centralwidget)
        self.line5_place5.setGeometry(QtCore.QRect(280, 230, 51, 31))
        self.line5_place5.setObjectName("line5_place5")
        self.line4_place5 = QtWidgets.QPushButton(self.centralwidget)
        self.line4_place5.setGeometry(QtCore.QRect(280, 190, 51, 31))
        self.line4_place5.setObjectName("line4_place5")
        self.line3_place5 = QtWidgets.QPushButton(self.centralwidget)
        self.line3_place5.setGeometry(QtCore.QRect(280, 150, 51, 31))
        self.line3_place5.setObjectName("line3_place5")
        self.line1_place5 = QtWidgets.QPushButton(self.centralwidget)
        self.line1_place5.setGeometry(QtCore.QRect(280, 70, 51, 31))
        self.line1_place5.setObjectName("line1_place5")
        self.line2_place5 = QtWidgets.QPushButton(self.centralwidget)
        self.line2_place5.setGeometry(QtCore.QRect(280, 110, 51, 31))
        self.line2_place5.setObjectName("line2_place5")
        self.line5_place6 = QtWidgets.QPushButton(self.centralwidget)
        self.line5_place6.setGeometry(QtCore.QRect(330, 230, 51, 31))
        self.line5_place6.setObjectName("line5_place6")
        self.line4_place6 = QtWidgets.QPushButton(self.centralwidget)
        self.line4_place6.setGeometry(QtCore.QRect(330, 190, 51, 31))
        self.line4_place6.setObjectName("line4_place6")
        self.line3_place6 = QtWidgets.QPushButton(self.centralwidget)
        self.line3_place6.setGeometry(QtCore.QRect(330, 150, 51, 31))
        self.line3_place6.setObjectName("line3_place6")
        self.line1_place6 = QtWidgets.QPushButton(self.centralwidget)
        self.line1_place6.setGeometry(QtCore.QRect(330, 70, 51, 31))
        self.line1_place6.setObjectName("line1_place6")
        self.line2_place6 = QtWidgets.QPushButton(self.centralwidget)
        self.line2_place6.setGeometry(QtCore.QRect(330, 110, 51, 31))
        self.line2_place6.setObjectName("line2_place6")
        self.line5_place7 = QtWidgets.QPushButton(self.centralwidget)
        self.line5_place7.setGeometry(QtCore.QRect(380, 230, 51, 31))
        self.line5_place7.setObjectName("line5_place7")
        self.line4_place7 = QtWidgets.QPushButton(self.centralwidget)
        self.line4_place7.setGeometry(QtCore.QRect(380, 190, 51, 31))
        self.line4_place7.setObjectName("line4_place7")
        self.line3_place7 = QtWidgets.QPushButton(self.centralwidget)
        self.line3_place7.setGeometry(QtCore.QRect(380, 150, 51, 31))
        self.line3_place7.setObjectName("line3_place7")
        self.line1_place7 = QtWidgets.QPushButton(self.centralwidget)
        self.line1_place7.setGeometry(QtCore.QRect(380, 70, 51, 31))
        self.line1_place7.setObjectName("line1_place7")
        self.line2_place7 = QtWidgets.QPushButton(self.centralwidget)
        self.line2_place7.setGeometry(QtCore.QRect(380, 110, 51, 31))
        self.line2_place7.setObjectName("line2_place7")
        self.line5_place8 = QtWidgets.QPushButton(self.centralwidget)
        self.line5_place8.setGeometry(QtCore.QRect(430, 230, 51, 31))
        self.line5_place8.setObjectName("line5_place8")
        self.line4_place8 = QtWidgets.QPushButton(self.centralwidget)
        self.line4_place8.setGeometry(QtCore.QRect(430, 190, 51, 31))
        self.line4_place8.setObjectName("line4_place8")
        self.line3_place8 = QtWidgets.QPushButton(self.centralwidget)
        self.line3_place8.setGeometry(QtCore.QRect(430, 150, 51, 31))
        self.line3_place8.setObjectName("line3_place8")
        self.line1_place8 = QtWidgets.QPushButton(self.centralwidget)
        self.line1_place8.setGeometry(QtCore.QRect(430, 70, 51, 31))
        self.line1_place8.setObjectName("line1_place8")
        self.line2_place8 = QtWidgets.QPushButton(self.centralwidget)
        self.line2_place8.setGeometry(QtCore.QRect(430, 110, 51, 31))
        self.line2_place8.setObjectName("line2_place8")
        self.line5_place9 = QtWidgets.QPushButton(self.centralwidget)
        self.line5_place9.setGeometry(QtCore.QRect(480, 230, 51, 31))
        self.line5_place9.setObjectName("line5_place9")
        self.line4_place9 = QtWidgets.QPushButton(self.centralwidget)
        self.line4_place9.setGeometry(QtCore.QRect(480, 190, 51, 31))
        self.line4_place9.setObjectName("line4_place9")
        self.line3_place9 = QtWidgets.QPushButton(self.centralwidget)
        self.line3_place9.setGeometry(QtCore.QRect(480, 150, 51, 31))
        self.line3_place9.setObjectName("line3_place9")
        self.line1_place9 = QtWidgets.QPushButton(self.centralwidget)
        self.line1_place9.setGeometry(QtCore.QRect(480, 70, 51, 31))
        self.line1_place9.setObjectName("line1_place9")
        self.line2_place9 = QtWidgets.QPushButton(self.centralwidget)
        self.line2_place9.setGeometry(QtCore.QRect(480, 110, 51, 31))
        self.line2_place9.setObjectName("line2_place9")
        self.line5_place10 = QtWidgets.QPushButton(self.centralwidget)
        self.line5_place10.setGeometry(QtCore.QRect(530, 230, 51, 31))
        self.line5_place10.setObjectName("line5_place10")
        self.line4_place10 = QtWidgets.QPushButton(self.centralwidget)
        self.line4_place10.setGeometry(QtCore.QRect(530, 190, 51, 31))
        self.line4_place10.setObjectName("line4_place10")
        self.line3_place10 = QtWidgets.QPushButton(self.centralwidget)
        self.line3_place10.setGeometry(QtCore.QRect(530, 150, 51, 31))
        self.line3_place10.setObjectName("line3_place10")
        self.line1_place10 = QtWidgets.QPushButton(self.centralwidget)
        self.line1_place10.setGeometry(QtCore.QRect(530, 70, 51, 31))
        self.line1_place10.setObjectName("line1_place10")
        self.line2_place10 = QtWidgets.QPushButton(self.centralwidget)
        self.line2_place10.setGeometry(QtCore.QRect(530, 110, 51, 31))
        self.line2_place10.setObjectName("line2_place10")
        self.buy = QtWidgets.QPushButton(self.centralwidget)
        self.buy.setGeometry(QtCore.QRect(440, 40, 75, 23))
        self.buy.setObjectName("buy")
        self.totals = QtWidgets.QTextEdit(self.centralwidget)
        self.totals.setGeometry(QtCore.QRect(480, 0, 101, 31))
        self.totals.setObjectName("totals")
        self.tickets = QtWidgets.QTextEdit(self.centralwidget)
        self.tickets.setGeometry(QtCore.QRect(380, 0, 101, 31))
        self.tickets.setObjectName("tickets")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Кинотеатр"))
        self.screen.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Экран</span></p></body></html>"))
        self.line1_place1.setText(_translate("MainWindow", "1"))
        self.line1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Ряд 1</span></p></body></html>"))
        self.line2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Ряд 2</span></p></body></html>"))
        self.line3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Ряд 3</span></p></body></html>"))
        self.line4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Ряд 4</span></p></body></html>"))
        self.line5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Ряд 5</span></p></body></html>"))
        self.line2_place1.setText(_translate("MainWindow", "1"))
        self.line3_place1.setText(_translate("MainWindow", "1"))
        self.line4_place1.setText(_translate("MainWindow", "1"))
        self.line5_place1.setText(_translate("MainWindow", "1"))
        self.line5_place2.setText(_translate("MainWindow", "2"))
        self.line4_place2.setText(_translate("MainWindow", "2"))
        self.line3_place2.setText(_translate("MainWindow", "2"))
        self.line1_place2.setText(_translate("MainWindow", "2"))
        self.line2_place2.setText(_translate("MainWindow", "2"))
        self.line5_place3.setText(_translate("MainWindow", "3"))
        self.line4_place3.setText(_translate("MainWindow", "3"))
        self.line3_place3.setText(_translate("MainWindow", "3"))
        self.line1_place3.setText(_translate("MainWindow", "3"))
        self.line2_place3.setText(_translate("MainWindow", "3"))
        self.line5_place4.setText(_translate("MainWindow", "4"))
        self.line4_place4.setText(_translate("MainWindow", "4"))
        self.line3_place4.setText(_translate("MainWindow", "4"))
        self.line1_place4.setText(_translate("MainWindow", "4"))
        self.line2_place4.setText(_translate("MainWindow", "4"))
        self.line5_place5.setText(_translate("MainWindow", "5"))
        self.line4_place5.setText(_translate("MainWindow", "5"))
        self.line3_place5.setText(_translate("MainWindow", "5"))
        self.line1_place5.setText(_translate("MainWindow", "5"))
        self.line2_place5.setText(_translate("MainWindow", "5"))
        self.line5_place6.setText(_translate("MainWindow", "6"))
        self.line4_place6.setText(_translate("MainWindow", "6"))
        self.line3_place6.setText(_translate("MainWindow", "6"))
        self.line1_place6.setText(_translate("MainWindow", "6"))
        self.line2_place6.setText(_translate("MainWindow", "6"))
        self.line5_place7.setText(_translate("MainWindow", "7"))
        self.line4_place7.setText(_translate("MainWindow", "7"))
        self.line3_place7.setText(_translate("MainWindow", "7"))
        self.line1_place7.setText(_translate("MainWindow", "7"))
        self.line2_place7.setText(_translate("MainWindow", "7"))
        self.line5_place8.setText(_translate("MainWindow", "8"))
        self.line4_place8.setText(_translate("MainWindow", "8"))
        self.line3_place8.setText(_translate("MainWindow", "8"))
        self.line1_place8.setText(_translate("MainWindow", "8"))
        self.line2_place8.setText(_translate("MainWindow", "8"))
        self.line5_place9.setText(_translate("MainWindow", "9"))
        self.line4_place9.setText(_translate("MainWindow", "9"))
        self.line3_place9.setText(_translate("MainWindow", "9"))
        self.line1_place9.setText(_translate("MainWindow", "9"))
        self.line2_place9.setText(_translate("MainWindow", "9"))
        self.line5_place10.setText(_translate("MainWindow", "10"))
        self.line4_place10.setText(_translate("MainWindow", "10"))
        self.line3_place10.setText(_translate("MainWindow", "10"))
        self.line1_place10.setText(_translate("MainWindow", "10"))
        self.line2_place10.setText(_translate("MainWindow", "10"))
        self.buy.setText(_translate("MainWindow", "Купить"))
        self.totals.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Итого:</p></body></html>"))
        self.tickets.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Билетов:</p></body></html>"))

